"""Add last_daily_claim_date to User

Revision ID: 003_daily_claims
Revises: 002_phase2_ml_schema
Create Date: 2024-02-12 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '003_daily_claims'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_daily_claim_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_daily_claim_date')
    # ### end Alembic commands ###
